---

- name: install apt prerequisites
  apt:
    name: apt-transport-https
    state: present

- name: install xinetd
  apt: name=xinetd state=present

- name: activate xinetd
  systemd: name=xinetd state=started enabled=true

- name: install checkmk_agent
  apt:
    deb: "http://{{ checkmk_agent_sources[0] }}/{{ checkmk_agent_site }}/check_mk/agents/check-mk-agent_{{ checkmk_agent_version }}_all.deb"
    state: present
